-- AlterTable
ALTER TABLE "NavLink" ALTER COLUMN "createdAt" SET DATA TYPE TIMESTAMPTZ(0),
ALTER COLUMN "updatedAt" SET DATA TYPE TIMESTAMPTZ(0);

-- AlterTable
ALTER TABLE "Prompt" ALTER COLUMN "createdAt" SET DATA TYPE TIMESTAMPTZ(0),
ALTER COLUMN "updatedAt" SET DATA TYPE TIMESTAMPTZ(0);

-- AlterTable
ALTER TABLE "ToolCard" ALTER COLUMN "createdAt" SET DATA TYPE TIMESTAMPTZ(0),
ALTER COLUMN "updatedAt" SET DATA TYPE TIMESTAMPTZ(0);
